### PR TITLE
examples: bailout gracefully if gdt package is not available

### PR DESCRIPTION
**Pull request by dev-zero**

### CODE REVIEW

**Comment by yakutovicha** [comment]
It seems to be working fine, just one question, when skipping test does it suppose to say nothing? Because to me, it shows only this:
Screenshot 2020-09-04 at 17 54 53

I believe one of the points of this PR was actually to tell to the user why tests are skipped.

**Comment by yakutovicha** [comment]
@dev-zero any thoughts on my previous comment?

**Comment by dev-zero** [comment]
> I believe one of the points of this PR was actually to tell to the user why tests are skipped.

here I get:

```terminal
$ pytest -v examples
platform linux -- Python 3.8.5, pytest-4.6.9, py-1.8.1, pluggy-0.13.1
rootdir: /home/tiziano/work/aiida/aiida-cp2k, inifile: pytest.ini
plugins: cov-2.8.1
collected 12 items / 2 skipped / 10 selected                                                                          

examples/single_calculations/example_dft.py
```

hence it shows that there are some tests which got skipped (you might want to check your terminals color scheme, I have the impression that you would see the same but you'd have to select a dark background since that report line is white here).

And as per [pytest documention](https://docs.pytest.org/en/latest/skipping.html#skip-and-xfail-dealing-with-tests-that-cannot-succeed) one has to pass `-rs` to get the information about skipped tests:

```terminal
$ pytest -rs test/test_gaussian_datatypes.py 
================================================= test session starts =================================================
platform linux -- Python 3.8.5, pytest-4.6.9, py-1.8.1, pluggy-0.13.1
rootdir: /home/tiziano/work/aiida/aiida-cp2k, inifile: pytest.ini
plugins: cov-2.8.1
collected 0 items / 1 skipped                                                                
[...]
=============================================== short test summary info ===============================================
SKIPPED [1] /home/tiziano/work/aiida/aiida-cp2k/test/test_gaussian_datatypes.py:27: Gaussian Datatypes are not available
======================================== 1 skipped, 3 warnings in 0.85 seconds ========================================
```

**Comment by dev-zero** [comment]
no idea why the tests started failing with this very strange error, but since the last patch was just nice to have I dropped it again

**Review by yakutovicha — APPROVED** [review]

**Comment by yakutovicha** [comment]
> no idea why the tests started failing with this very strange error, but since the last patch was just nice to have I dropped it again

I think it is because of the recent update of aiida-core: https://github.com/aiidateam/aiida-core/issues/4359

**Pull request merged**
