### PR TITLE
Aiida 1.0 compat

### PR DESCRIPTION
**Pull request by dev-zero**
For the record, here is my AiiDA-1.0/python-3 compatibility branch

### CODE REVIEW

**Comment by dev-zero** [comment]
@yakutovicha my PR is a bit more invasive. One of the differences is that I adapted the tests to be run properly with pyunit. And that everything is Python-3.6+ only due to the timeframe (Python-2 supports ends this year), mostly due to the f-strings (could be changed back again, though).

**Comment by yakutovicha** [comment]
Hi @dev-zero. I according to our internal discussions, aiida will keep supporting python2 at least till the end of this year. So the goal we set up for ourselves is make as much plugins as possible python2/3 compatible as well.

There are certain things that wouldn't work in your current version of the plugin. For example the following way of specifying inputs is not supported anymore:
```
"structure": {
'valid_types': StructureData,
'additional_parameter': None,
 'linkname': 'structure',
  'docstring': "Choose the input structure to use",
  },
```
[Here](https://github.com/aiidateam/aiida_core/wiki/AiiDA-1.0-plugin-migration-guide) you can find the draft of the migration guide.

A suggestion from my side would be: I merge my PR (which is already working) and then we discuss your design decisions during the plugin migration week and implement them upon agreement. Currently I am on vacations, so won't be much available this week.

**Comment by dev-zero** [comment]
> Hi @dev-zero. I according to our internal discussions, aiida will keep supporting python2 at least till the end of this year. So the goal we set up for ourselves is make as much plugins as possible python2/3 compatible as well.

@yakutovicha well, those are the guidelines for AiiDA, and I see why you want to follow them in the plugins as well and eventually I would have brought back Python 2 support, but I wanted to start from something more clean and then introduce back-compatibility.

> 
> There are certain things that wouldn't work in your current version of the plugin. For example the following way of specifying inputs is not supported anymore:
> 
> ```
> "structure": {
> 'valid_types': StructureData,
> 'additional_parameter': None,
>  'linkname': 'structure',
>   'docstring': "Choose the input structure to use",
>   },
> ```
> [Here](https://github.com/aiidateam/aiida_core/wiki/AiiDA-1.0-plugin-migration-guide) you can find the draft of the migration guide.

Thanks, that guide didn't exist when I started :( or it didn't show up in Google searches.

> A suggestion from my side would be: I merge my PR (which is already working) and then we discuss your design decisions during the plugin migration week and implement them upon agreement. Currently I am on vacations, so won't be much available this week.

Well, I can do another PR based on your code with the pylint-compatible tests plus some of the other changes/bugfixes I have.

**Comment by yakutovicha** [comment]
@dev-zero yeah, that is unfortunate that we started to work on the plugin migration separately. Working together would require much less time. 

Also, just to make you aware: I will most probably squash my commits into a single one, it order to make the history less polluted. And then will merge it into master.

**Comment by dev-zero** [comment]
@yakutovicha https://github.com/aiidateam/aiida-cp2k/network is otherwise a good way to check for (public) activity and is what I used to determine whether someone was already working on it

**Pull request closed without merging**
