### PR TITLE
Let SCF iteration converge for this test, because an SCF convergence …

### PR DESCRIPTION
**Pull request by mkrack**
…failure is now an error and causes an abort.

### CODE REVIEW

**Comment by mkrack** [comment]
This PR works fine for me locally using [this docker file](https://github.com/mkrack/cp2k/blob/master/tools/docker/Dockerfile.test_aiida) and it should resolve the current issue with the regression test for the [AiiDA-CP2K plugin](https://dashboard.cp2k.org/archive/aiida/index.html).
@yakutovicha Please, could you have a look?

**Review by yakutovicha — APPROVED** [review]
LGTM, thanks @mkrack!

**Comment by oschuett** [comment]
I'm afraid the test is still rather flaky as it [fails roughly every other time](https://dashboard.cp2k.org/archive/aiida/index.html).

**Comment by oschuett** [comment]
Is there no other way? If you mock out cp2k then this test will be far less useful.
Maybe we could just set [IGNORE_CONVERGENCE_FAILURE](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT/SCF.html#CP2K_INPUT.FORCE_EVAL.DFT.SCF.IGNORE_CONVERGENCE_FAILURE) to restore the old behavior?

**Pull request merged**
