### PR TITLE
Review fixes

### PR DESCRIPTION
**Pull request by dev-zero**
@yakutovicha fixes based on @ltalirz and my review

### CODE REVIEW

**Comment by dev-zero** [comment]
btw, the current TravisCI configuration seems to be faulty and does not catch errors from modernize or yapf pre-commit hooks.

**Comment by yakutovicha** [comment]
thanks @dev-zero. Is it fine if I squash your commits into a single one?

**Comment by dev-zero** [comment]
I don't think that makes sense since the changes touch different subjects, but ultimately I don't care

**Comment by dev-zero** [comment]
@yakutovicha the test failures after my last commit are likely not mine but are from the aiida upgrade, I only fixed your typo in the `run_tests.sh` which prevented Travis from noticing them (check the output for previous successful tests).

**Pull request merged**
