### PR TITLE
cell optimization handler

### PR DESCRIPTION
**Pull request by VasylStotskyi**
Initial attempt

### CODE REVIEW

**Comment by yakutovicha** [comment]
I will close the PR as according to our current understanding, restarting the simulation wouldn't change anything. See [here](https://groups.google.com/g/cp2k/c/_1K-srPeWE4/m/uePL3MZ2AQAJ) for more details.

**Comment by VasylStotskyi** [comment]
Sure. That's make sense, but please don't forget that there also was fix
for structure calculations (previously during restart plugin used old
structure from database to restart while it had to use the last obtained.

**Comment by yakutovicha** [comment]
> Sure. That's make sense, but please don't forget that there also was fix for structure calculations (previously during restart plugin used old structure from database to restart while it had to use the last obtained.

Right, thanks for reminding me. Can you make another PR with that change only?

**Comment by VasylStotskyi** [comment]
Dear Aliaksandr,
I'm sorry, I forgot to send you pull request. I will do this today, when I
return home or max on Wednesday.
Sorry for delay.
Best wishes,
Vasyl

**Pull request closed without merging**
